---
- name: 0. Ubuntu. Add ppa repo
  apt_repository:
    repo: 'ppa:vbernat/haproxy-1.8'
    codename: bionic

- name: 1. Ubuntu. Update packages
  apt:
    update_cache: yes

- name: 2. Ubuntu. Install haproxy
  apt:
    name:
      - haproxy
  ignore_errors: yes

- name: 3. Ubuntu. Start haproxy
  systemd:
    name: haproxy
    state: started
    enabled: no
  ignore_errors: yes
