version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: ../src/config
    ports:
      - 8888:8888

  registry:
    build: ../src/registry

  gateway:
    build: gateway

  auth-service:
    build: ../src/auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: ../services/mongodb
    ports:
      - 25000:27017

  account-service:
    build: ../src/account-service
    ports:
      - 6000:6000

  account-mongodb:
    build: ../services/mongodb
    ports:
      - 26000:27017

  statistics-service:
    build: ../src/statistics-service
    ports:
      - 7000:7000

  statistics-mongodb:
    build: ../services/mongodb
    ports:
      - 27000:27017

  notification-service:
    build: ../src/notification-service
    ports:
      - 8000:8000

  notification-mongodb:
    build: ../services/mongodb
    ports:
      - 28000:27017

  monitoring:
    build: ../src/monitoring

  turbine-stream-service:
    build: ../src/turbine-stream-service