apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: develop
  labels:
    app: auth-service
    sub: stage-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth-service
      sub: stage-app
  template:
    metadata:
      labels:
        app: auth-service
        sub: stage-app
    spec:
      containers:
        - name: auth-service
          image: docker.pkg.github.com/badgersolutions/otus-devops-final-project/piggymetrics_auth-service:1.0
          env:
          - name: CONFIG_SERVICE_PASSWORD
            value: SecureP@ssw0rd
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: SecureP@ssw0rd
          - name: STATISTICS_SERVICE_PASSWORD
            value: SecureP@ssw0rd
          - name: ACCOUNT_SERVICE_PASSWORD
            value: SecureP@ssw0rd
          - name: MONGODB_PASSWORD
            value: piggy
          - name: MONGODB_URI
            value: mongodb://10.0.1.26:27017,10.0.1.27:27017/?replicaSet=mongo_cluster1
          - name: MONGODB_USER
            value: piggy
          - name: AUTH_DATABASE
            value: auth
      imagePullSecrets:
        - name: github-pkg
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: develop
  labels:
    app: auth-service
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: auth-service
    sub: stage-app
