apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: stage
  labels:
    app: notification-service
    sub: stage-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: notification-service
      sub: stage-app
  template:
    metadata:
      labels:
        app: notification-service
        sub: stage-app
    spec:
      containers:
        - name: notification-service
          image: docker.pkg.github.com/badgersolutions/otus-devops-final-project/piggymetrics_notification-service:1.0
          env:
          - name: MONGODB_PASSWORD
            value: SecureP@ssw0rd
          - name: CONFIG_SERVICE_PASSWORD
            value: SecureP@ssw0rd
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: SecureP@ssw0rd
      imagePullSecrets:
        - name: github-pkg
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: stage
  labels:
    app: notification-service
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: notification-service
    sub: stage-app
