- name: 0. Ubuntu. Commenting a line in fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap.*)'
    replace: '#\1'

- name: 1. Ubuntu. Unmount swapfile
  mount:
    name: swap
    fstype: swap
    state: absent

- name: 2. Ubuntu. Disable swap
  shell:
    cmd:
      swapoff -a
  args:
    executable: /bin/bash
