- name: 0. Ubuntu. Install Elasticsearch v7.5.2
  apt:
    deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.2-amd64.deb

- name: 1. Ubuntu. Stop elasticsearch
  systemd:
    name: elasticsearch
    state: stopped
  ignore_errors: yes
