apiVersion: v1
kind: Service
metadata:
  name: {{ include "config.fullname" . }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "config.selectorLabels" . | nindent 4 }}
