---
- name: 0. Ubuntu. Edit nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: yes
    backup: no
    validate: nginx -c %s -t
  notify: reload nginx

- name: 1. Ubuntu. Edit upstream-alone.conf
  template:
    src: conf.d/upstream-alone.conf.j2
    dest: /etc/nginx/conf.d/upstream-alone.conf
    force: yes
    backup: no
    validate: bash -c 'nginx -t && echo %s'
  notify: reload nginx

- name: 2. Ubuntu. Edit sites configs
  template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item | basename | regex_replace('\.j2','') }}
    force: yes
    backup: no
    validate: bash -c 'nginx -t && echo %s'
  with_fileglob:
    - templates/conf.d/*.j2
  notify: reload nginx

- name: 3. Ubuntu. Edit sysctl.conf
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes
