spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
