spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${AUTH_DATABASE}
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
